### ISSUE TITLE
solution was already completed

### ISSUE THREAD

**Issue by DeCode2018** [learn-co-curriculum/method-arguments-lab#10]
For this lab, it automatically showed complete before I did anything.  I went ahead and cloned the lab anyway to see if I could solve it on my own but the cloned version when I run "learn" (without me making any changes) the lab passes all test.

**Comment by maxwellbenton** [comment]
Hi there @DeCode2018,

I've taken a look at this repository and at your fork. From what I see, you're part of web-082718, is that correct? This lab may also exist in the free/intro tracks on learn.co and it looks like you already forked the lab while in one of these tracks. Learn.co recognizes you've already completed the lab and will likely pull your previous solution when you are forking and cloning the lab down.

It may be good to review the content of the lab, but otherwise, you should be all set to continue on.

If you do not feel this is the cause of this issue, please feel free to reopen this issue and I'd be happy to take a second look!

As always, thanks for contributing! 💙
